version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/wd
    steps:
      # if markdown includes characters other than ascii (e.g. Japanese) you needs to install fonts like below
      # - run: sudo apt-get update && sudo apt-get install fonts-ipaexfont -y
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/wd/node_modules
      - run: npm run build
      - deploy:
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL > credential.json
            dirname=`date +%Y%m%d_%H%M%S` && mv build $dirname
            ./gdrive --config `pwd` --service-account credential.json upload -p parent_folder_id_here -r $dirname